version: "3.6"
services:
  postgres:
    image: postgres:13.1
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data: {}
